CREATE TABLE "cars" (
	"id" serial PRIMARY KEY NOT NULL,
	"name" text NOT NULL,
	"slug" text NOT NULL,
	"image_url" text NOT NULL,
	"mileage_km" integer NOT NULL,
	"first_registration" text NOT NULL,
	"power_kw" integer NOT NULL,
	"power_hp" integer NOT NULL,
	"transmission" text NOT NULL,
	"fuel_type" text NOT NULL,
	"location_country" text NOT NULL,
	"delivery_price_czk" integer NOT NULL,
	"monthly_payment_czk" integer NOT NULL,
	"total_price_czk" integer NOT NULL,
	"vat_price_czk" integer NOT NULL,
	"price_rating_label" text NOT NULL,
	"partner_label" text NOT NULL,
	"equipment_tags" text[] DEFAULT '{}' NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "cars_slug_unique" UNIQUE("slug")
);
